spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.56.101
    port: 6379
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:/SpringLearningFile/log
#  file: D:/SpringLearningFile/log/sell.log
#  level:
#    com.akie.LoggerTest: debug
##    root: debug
wechat:
    mpAppId: wx8d265226aa667d75
    mpAppSecret: 24cea323bdb7ad4bc31d97eadc4947a2
    openAppId: wx6ad144e54af67d87
    openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
    mchId: 1483469312
    mchKey: 06C56A89949D617xxxxxxxxxxx
    keyPath: /var/weixin_cert/h5.p12
    notifyUrl: http://akiesell.natapp1.cc/sell/pay/notify
    templateId:
#      微信公众号推送消息模板的id，以及id的类型
      orderStatus: bPModO1mmbilUcDuXKNb8BPKxwK1xrgow3bWurhTXX8

projecturl:
  wechatMpAuthorize: http://akiesell.natapp1.cc
#  http://127.0.0.1:8080
  wechatOpenAuthorize: http://akiesell.natapp1.cc
#  http://127.0.0.1:8080
  sell: http://akiesell.natapp1.cc
#  http://127.0.0.1:8080

#日志的使用 打印使用mybatis的sql语句
logging:
  level:
    com.akie.dataobject.mapper: trace
mybatis:
  #放在resource目录下这里使用classpath
  mapper-locations: classpath:mapper/*.xml

